[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "turnstile-solver"
version = "0.1.0"
description = "Python-based turnstile solver using the patchright library, featuring multi-threaded execution, API integration, and support for different browsers."
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
dependencies = [
    "quart",
    "patchright",
    "camoufox[geoip]",
    "hypercorn"
]

[project.urls]
Homepage = "https://github.com/Theyka/Turnstile-Solver"
